# Generated by Django 4.2.7 on 2023-11-25 15:18

from django.db import migrations, models
import django.db.models.deletion
import system.func


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DP_account_id', models.CharField(max_length=64, unique=True)),
                ('AT_account_password', models.CharField(blank=True, default=system.func.token, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LoginBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DP_AT_login_req_id', models.CharField(default=system.func.token, max_length=128)),
                ('DP_login_account_id', models.CharField(max_length=64)),
                ('AT_lifetime', models.DateTimeField(default=system.func.lifetime)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DP_AT_device_id', models.CharField(default=system.func.id, max_length=128, unique=True)),
                ('AT_login_token', models.CharField(default=system.func.id, max_length=128)),
                ('permission_level', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.account')),
            ],
        ),
    ]
