# Generated by Django 4.2.7 on 2023-11-25 17:21

from django.db import migrations, models
import django.db.models.deletion
import system.func


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbridge',
            name='NA_allow_device',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='AT_login_token',
            field=models.CharField(default=system.func.token, max_length=128),
        ),
    ]
